//
// Created by ASUS on 4/12/2026.
//

#ifndef MINI_BACKEND_SYSTEM_INMEMORYTASKSTORAGE_H
#define MINI_BACKEND_SYSTEM_INMEMORYTASKSTORAGE_H


class InMemoryTaskStorage {

};


#endif //MINI_BACKEND_SYSTEM_INMEMORYTASKSTORAGE_H
